Develop 15 sphinx
iL53n/qna pull request #14
Opened 2019-09-03 15:17 UTC by iL53n

2019-09-04 08:46 UTC, vkurennov requested changes

2019-09-04 08:46 UTC, vkurennov commented on app/controllers/search_controller.rb
> +  RESOURCE = %w[All Question Answer Comment User]
хорошо бы сделать сервисный класс для поиска и вызвать его в контроллере, а то многовато логики для контроллера получаетя.

2019-09-04 08:46 UTC, vkurennov commented on app/controllers/search_controller.rb
> +    @q_text = search_params[:q]
запрос надо эскейпить, т.к. могут быть управляющие символы. в доке по сфинксу это показано в примерах

2019-09-04 08:46 UTC, vkurennov commented on spec/features/search/search_spec.rb
> +    scenario 'question' do
надо на всех вариантах тестировать

2019-09-04 08:46 UTC, vkurennov commented on sphinxdata/logs/searchd.log
> +[Sun Sep  1 20:27:47.701 2019] [-1] watchdog: main process 95386 forked ok
это в .gitignore и удали из репо

2019-09-04 08:46 UTC, vkurennov commented on sphinxdata/searchd.state
> +{
это тоже в .gitignore

2019-09-04 19:12 UTC, iL53n commented on sphinxdata/logs/searchd.log
> +[Sun Sep  1 20:27:47.701 2019] [-1] watchdog: main process 95386 forked ok
+

2019-09-04 19:13 UTC, iL53n commented on sphinxdata/searchd.state
> +{
add

2019-09-04 21:59 UTC, iL53n commented on app/controllers/search_controller.rb
> +  RESOURCE = %w[All Question Answer Comment User]
сделал `Services::Search`

2019-09-04 21:59 UTC, iL53n commented on spec/features/search/search_spec.rb
> +    scenario 'question' do
add

2019-09-04 22:26 UTC, iL53n commented on app/controllers/search_controller.rb
> +    @q_text = search_params[:q]
не уверен...
`@q_text = ThinkingSphinx::Query.escape(params[:q])`

2019-09-05 08:09 UTC, vkurennov requested changes

2019-09-05 08:09 UTC, vkurennov commented on app/controllers/search_controller.rb
> +  def call_service
в методе одна строка, стоит вынести его на место вызова, все равно повторно он нигде не используется, поэтому применение метода здесь не оправдано

2019-09-05 08:09 UTC, vkurennov commented on app/services/search.rb
> +class Services::Search
стоит предусмотреть (и протестировать) ситуацию, когда передан не поддерживаемый ресурс

2019-09-05 08:09 UTC, vkurennov commented on spec/features/search/search_spec.rb
> +    scenario 'question' do
сценарии должны быть для каждого возможного варианта. не только в юнит-тестах, но и в фича-тестах тоже

2019-09-05 20:53 UTC, iL53n commented on app/controllers/search_controller.rb
> +  def call_service
correct

2019-09-05 20:53 UTC, iL53n commented on app/services/search.rb
> +class Services::Search
add

2019-09-06 07:33 UTC, vkurennov approved these changes

2019-09-06 07:33 UTC, vkurennov commented on app/services/search.rb
> +  def r_include?
и опять метод тут ни к чему. тут одна строка, она больше нигде не повторяется, так почему бы просто не написать ее в месте вызова?

2019-09-06 09:22 UTC, iL53n commented on app/services/search.rb
> +  def r_include?
убрал

2019-09-06 09:23 UTC, merged