Develop 5
iL53n/qna pull request #3
Opened 2019-06-16 21:40 UTC by iL53n

2019-06-17 13:31 UTC, vkurennov requested changes

2019-06-17 13:31 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user)
user не приходит в параметрах, мы его получаем в контроллере через current_user

2019-06-17 13:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def show; end
для ответа не доложно быть отдельной страницы. список ответов со всеми элементами, такими как ссылка на удаление должны быть на странице вопроса

2019-06-17 13:31 UTC, vkurennov commented on app/views/answers/show.html.slim
> += render 'shared/errors', resource: @answer
для ответа не доложно быть отдельной страницы. список ответов со всеми элементами, такими как ссылка на удаление должны быть на странице вопроса

2019-06-17 13:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +p= link_to 'Delete question', question_path(@question), method: :delete
ссылку стоит показывать только автору, а не всем подряд

2019-06-17 13:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render 'shared/errors', resource: @question
зачем тут это? у тебя ошибки в questions/new выводятся, там же, где и форма

2019-06-17 13:31 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
нужно проверить еще и связь с залогиненным юзером

2019-06-17 13:31 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to render_template :show
рендериться должен questions/show, как у тебя в контроллере и написано. Прогоняй тесты перед сдачей, они укажут на ошибки

2019-06-17 13:31 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>        it 'saves a new question in the database' do
тут нужно проверить связь с залогиненным юзером

2019-06-17 13:31 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +    click_on 'Delete answer'
лучше не показывать ссылку на удаление всем подряд, а только автору

2019-06-17 13:31 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +    click_on 'Delete answer'
и тут тоже лучше не показыать ссылку

2019-06-17 13:31 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +    expect(page).to have_content 'The question are destroyed'
надо еще проверить, что вопроса больше нет на странице

2019-06-17 13:31 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +    click_on 'Delete question'
и тут тоже лучше не показыать ссылку

2019-06-17 13:31 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +    click_on 'Delete question'
и тут тоже лучше не показыать ссылку

2019-06-17 13:31 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +    expect(page).to have_content 'The answer are destroyed'
тут надо проверить, что ответа больше нет на странице

2019-06-17 13:31 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
где тесты на метод `author_of?`? Любой код, который ты пишешь в каком-либо классе должен быть покрыт тестами

2019-06-17 13:31 UTC, vkurennov commented on spec/features/question/index_spec.rb
> +    questions.each do |question|
тест верный, но он ложно-положительный, т.к. все вопросы у тебя одинаковые и даже если на странице будет один вопрос, то тест все равно пройдет. нужно сделать вопросы разными, лучше всего через sequence в фабриках

2019-06-17 13:31 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    question.answers.each { |answer| expect(page).to have_content answer.body }
ответы тоже надо сделать разными

2019-06-17 15:47 UTC, iL53n commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user)
убрал

2019-06-17 17:00 UTC, iL53n commented on app/controllers/answers_controller.rb
> +  def show; end
убрал, реализовал на странице ответа

2019-06-17 17:00 UTC, iL53n commented on app/views/answers/show.html.slim
> += render 'shared/errors', resource: @answer
удалил show

2019-06-17 17:01 UTC, iL53n commented on app/views/questions/show.html.slim
> +p= link_to 'Delete question', question_path(@question), method: :delete
добавил условие `author?`

2019-06-17 17:03 UTC, iL53n commented on app/views/questions/show.html.slim
> += render 'shared/errors', resource: @question
а если удаление вопроса не прошло? где выводить сообщение?

2019-06-17 17:05 UTC, iL53n commented on spec/features/answer/destroy_spec.rb
> +    click_on 'Delete answer'
добавил условие `author?`

2019-06-17 17:06 UTC, iL53n commented on spec/features/answer/destroy_spec.rb
> +    click_on 'Delete answer'
убрал, проверяю отсутсиве кнопки 'Delete answer'

2019-06-17 17:06 UTC, iL53n commented on spec/features/question/destroy_spec.rb
> +    expect(page).to have_content 'The question are destroyed'
добавил
```
    expect(page).to_not have_content question.title
    expect(page).to_not have_content question.body
```

2019-06-17 17:07 UTC, iL53n commented on spec/features/question/destroy_spec.rb
> +    click_on 'Delete question'
убрал, проверяю отсутсиве кнопки 'Delete answer'
```
expect(page).to_not have_content 'Delete question'
```

2019-06-17 17:07 UTC, iL53n commented on spec/features/question/destroy_spec.rb
> +    click_on 'Delete question'
убрал, проверяю отсутсиве кнопки 'Delete answer'
```
expect(page).to_not have_content 'Delete question'
```

2019-06-17 17:09 UTC, iL53n commented on spec/features/answer/destroy_spec.rb
> +    expect(page).to have_content 'The answer are destroyed'
добавил
```
expect(page).to_not have_content answer.body
```

2019-06-17 17:10 UTC, iL53n commented on spec/features/question/index_spec.rb
> +    questions.each do |question|
добавил
```
  sequence :title do |n|
    "Question_#{n}_title"
  end
```

2019-06-17 17:11 UTC, iL53n commented on spec/features/question/show_spec.rb
> +    question.answers.each { |answer| expect(page).to have_content answer.body }
добавил
```
  sequence :body do |n|
    "Answer_#{n}_body"
  end
```

2019-06-17 17:19 UTC, iL53n commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
добавил, если правильно понял
`...to change(user.answers, :count).by(1)`

2019-06-17 17:26 UTC, iL53n commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to render_template :show
тест с `expect(response).to render_template :show` проходит.

2019-06-17 17:30 UTC, iL53n commented on spec/controllers/questions_controller_spec.rb
>        it 'saves a new question in the database' do
доавил, если правльно понял `...to change(user.questions, :count).by(1)`

2019-06-17 17:58 UTC, iL53n commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
добавил

2019-06-18 08:00 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render 'shared/errors', resource: @question
здесь у тебя выводятся ошибки **валидации**, валидация выполняется только при создании и обновлении объекта, при удалении она не выполняется (что логично, зачем проверять правильность данных объекта, если а) он уже есть, т.е. правильность уже когда-то проверилти, б) мы его удаляем и без разницы валидный он или нет, раз он больше не нужен). Как выводить ошибки, если объект не был удален (что в теории возможно) - решает сам разработчик. можно это сделать через флеш-сообщения, например.

2019-06-18 08:01 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to render_template :show
хм, возможно, тесты не учитывают путь в таком случае. раз ты ренедришь question/show, то show тоже проходит. но лучше явно указать в данном случае.

2019-06-18 08:06 UTC, vkurennov approved these changes

2019-06-18 08:06 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      it 'saves a new user question in the database' do
здесь достаточно только этого теста, т.к. он включает в себя предыдущий.

2019-06-18 08:06 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +    expect(page).to_not have_content 'Delete answer'
лучше использовать have_link для проверки ссылок

2019-06-18 08:06 UTC, vkurennov commented on spec/models/user_spec.rb
> +  describe 'user.author?' do
Для описания инстанс-методов принят формат `describe '#method'`, решетка означает, что это именно инстанс-метод (для методов класса испольузется точка). Имя класса не пишем, потому что оно есть в корневом describe

2019-06-18 08:06 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user_author.author?(question)).to eq true
rspec для методов-предикатов умеет делать динамические матчеры, и можно писать так:

`expect(user).to be_author(question)`.

Т.е. переносим вызов метода после to, добавляем be_ и убираем вопросительный знак. Легко читать и понимать. А если метод назвать `author_of?`, то еще и красиво получится

2019-06-18 17:22 UTC, iL53n commented on app/views/questions/show.html.slim
> += render 'shared/errors', resource: @question
вопрос как раз был 

> Как выводить ошибки, если объект не был удален (что в теории возможно)

спасибо, теперь понял

2019-06-18 17:23 UTC, iL53n commented on spec/controllers/questions_controller_spec.rb
> +      it 'saves a new user question in the database' do
логично, убрал

2019-06-18 17:26 UTC, iL53n commented on spec/features/answer/destroy_spec.rb
> +    expect(page).to_not have_content 'Delete answer'
заменил на `to_not have_link question_path(question)`

2019-06-18 17:33 UTC, iL53n commented on spec/features/answer/destroy_spec.rb
> +    expect(page).to_not have_content 'Delete answer'
и в question заменил

2019-06-18 17:33 UTC, iL53n commented on spec/models/user_spec.rb
> +  describe 'user.author?' do
переименовал

2019-06-18 17:41 UTC, iL53n commented on spec/models/user_spec.rb
> +      expect(user_author.author?(question)).to eq true
заменил, переименовал

2019-06-18 17:46 UTC, merged