Develop 8
iL53n/qna pull request #6
Opened 2019-07-08 20:47 UTC by iL53n

2019-07-09 07:29 UTC, vkurennov requested changes

2019-07-09 07:29 UTC, vkurennov commented on .env
> +GITHUB_TOKEN = {
и вот ты на весь мир засветил свои логин и пароль. срочно меняй пароль и никогда так не делай. во-первых, .env не кладется в репозиторий, во-вторых, есть более удобный способ - использовать credentials для хранения таких вещей. его можно и в репо положить, но он шифрованный, так что это безопасно. в третьих, зачем вообще тебе здесь понадобились логин и пароль от твоего гитхаба?

2019-07-09 07:29 UTC, vkurennov commented on app/controllers/links_controller.rb
> +      render plain: 'Forbidden', status: 403
лучше так: `head :forbidden`

2019-07-09 07:29 UTC, vkurennov commented on spec/controllers/links_controller_spec.rb
> +      it 'question' do
это лишнее, удаление аттачмента не зависит от типа родительского объекта, поэтому не нужно проверять на разных. достаточно проверить что в принципе удаляется аттачмент, без учета его связей.

2019-07-09 07:29 UTC, vkurennov commented on spec/controllers/links_controller_spec.rb
> +    context 'User tries to delete link in not his' do
тут то же самое: не нужно привязываться к типу родителького объекта

2019-07-09 07:29 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      user.rewards.each do |reward|
это бессмысленная проверка, потому что так ты проверяшь работу ассоциаций, но это работа фреймворка, а его мы не тестируем. достаточно проверить наличие ассоциации так, как мы это делаем для вопроса и юзера. Ну и кроме того, если у юзера вообще не будет наград тест пройдет, т.к. цикл не выполнится. т.е. он еще и ложно-положительный.

Поэтому надо придумать другой способ проверки того, что у юзера появилась награда.

2019-07-09 07:29 UTC, vkurennov commented on spec/features/answer/best_spec.rb
> -    scenario 'choice best answer for his question',js: true do
тут нужен сценарий на получение награды

2019-07-09 09:51 UTC, iL53n commented on .env
> +GITHUB_TOKEN = {
1. пароль, логин сменил
2. credentials - почитал доки, взял на вооружение
3. глупость моя. почему-то решил, что нужно аутентифицироваться, чтобы прочитать гист

2019-07-09 09:54 UTC, iL53n commented on app/controllers/links_controller.rb
> +      render plain: 'Forbidden', status: 403
заменил

2019-07-09 10:15 UTC, iL53n commented on spec/controllers/links_controller_spec.rb
> +      it 'question' do
убрал

2019-07-09 10:15 UTC, iL53n commented on spec/controllers/links_controller_spec.rb
> +    context 'User tries to delete link in not his' do
убрал

2019-07-09 15:14 UTC, iL53n commented on spec/models/answer_spec.rb
> +      user.rewards.each do |reward|
если правильно понял, нужно проверить, что юзер лучшего ответа имеет нагруду фопроса к этому ответу. получается

2019-07-09 16:54 UTC, iL53n commented on spec/features/answer/best_spec.rb
> -    scenario 'choice best answer for his question',js: true do
добавил

2019-07-10 08:16 UTC, vkurennov approved these changes

2019-07-10 08:20 UTC, merged